language: php
php:
  - "8.0"

cache:
  directories:
    - $HOME/.composer/cache

env:
  - PHPUNIT_VERSION=9.* TESTBENCH_VERSION=6.*

before_script:
  - travis_retry composer self-update
  - travis_retry composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update
  - travis_retry composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update
  - travis_retry composer update --no-interaction --prefer-source

script:
  - php vendor/bin/phpunit
